from __future__ import annotations


ROUTE_DEPENDENCIES = (
    "ACCOUNTS_PATH",
    "DEFAULT_OPERATOR",
    "DEFAULT_TEMPLATE",
    "JOBS",
    "JOBS_LOCK",
    "PENDING_ACCOUNTS",
    "PENDING_ACCOUNTS_LOCK",
    "RUN_ROOT",
    "SHOP_ID",
    "TEMPLATES",
    "UPLOAD_ROOT",
    "account_credentials",
    "account_module",
    "active_account_job_id",
    "active_job_id_unlocked",
    "ai_requests",
    "ai_settings_from_form",
    "alert_html",
    "all_account_ids",
    "batch_requests",
    "build_preflight_failures",
    "build_product_attributes",
    "call_deepseek_ai",
    "clean_prefix",
    "decimal_field",
    "discover_templates",
    "e",
    "field_list",
    "field_text",
    "get_category_metadata",
    "image_seq_dirs",
    "int_field",
    "job_module",
    "load_accounts_config",
    "parse_sku_rows",
    "read_items",
    "readable_error_text",
    "render_account_confirm",
    "render_account_menu",
    "render_accounts",
    "render_ai_settings",
    "render_failure_page",
    "render_home",
    "render_job",
    "render_page",
    "render_release_check",
    "render_single",
    "render_top_nav",
    "require_english",
    "resolve_image_layout",
    "save_ai_settings",
    "save_upload",
    "settings_for_ai_test",
    "single_requests",
    "stage_batch_images",
    "start_job",
    "start_single_job",
    "test_ai_settings",
    "upload_filename",
    "uploaded_image_files",
    "uploaded_sku_image_files",
    "uploaded_video_file",
)


def route_deps(namespace: dict[str, object]) -> dict[str, object]:
    return {name: namespace[name] for name in ROUTE_DEPENDENCIES}
